apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcareapp-eta-deploy
  labels:
    app: healthcareapp-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcareapp-eta-app
  template:
    metadata:
      labels:
        app: healthcareapp-eta-app
    spec:
      containers:
      - name: healthcareapp-eta-container
        image: asharenu08/healthcareapp-eta-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcareapp-eta-np-service
  labels:
    app: healthcareapp-eta-app
spec:
  selector:
    app: healthcareapp-eta-app

  type: NodePort
  ports:
  - nodePort: 31035
    port: 8082
    targetPort: 8082
